include:
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DZMK_KEYBOARD_NAME=KorneKball
    artifact-name: corne_left
    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DZMK_KEYBOARD_NAME=KorneKball
    artifact-name: corne_right
    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
