
---
include:
  # Corne left half (nice_nano_v2, no display/LED)
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DZMK_KEYBOARD_NAME=KorneKball
    artifact: corne_left
    snippet: zmk-usb-logging

  # Corne right half (nice_nano_v2, no display/LED)
  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DZMK_KEYBOARD_NAME=KorneKball
    artifact: corne_right
    snippet: zmk-usb-logging
    
  # Settings reset (flash first to clear BT bonds)
  - board: nice_nano_v2
    shield: settings_reset
    artifact: settings_reset
